<a href="https://colab.research.google.com/github/grant88/education/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
n = 10
x = np.arange(n - 1, -1, -1)
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
matrix = np.diag(x)
matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
# Сумма значений по диагонали
np.trace(matrix)

45

**Задание 3**

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [7]:
from numpy import linalg

In [8]:
coefficients = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])

In [9]:
values = np.array([
    4,
    12,
    -3
])

In [10]:
x, y, z = linalg.solve(coefficients, values)
x, y, z

(0.4666666666666668, 3.844444444444444, -5.555555555555555)

Проверка того, что найденные x, y, z удовлетворяют условиям уравнения:

In [11]:
[int(round(x.sum(), 0)) for x in coefficients * np.array([x, y, z])] == values

array([ True,  True,  True])

**Задача 4**

Имеется матрица покупок в интернет-магазине.

Столбец А - ID пользователя.

Остальные столбцы - количество покупок категорий товаров этим пользователем

Матрица в виде numpy array:

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [13]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найти самого похожего пользователя. 
Т. е. посчитать косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

**Решение задачи 4**

In [14]:
from numpy import dot
from numpy import linalg

In [15]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

Косинусные расстояния между новым пользователем и пользователями из массива user_stats

In [16]:
cos_distanses = [cosine(user, next_user_stats) for user in users_stats]
cos_distanses

[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]

Максимальное косинусное расстояние

In [17]:
max_cos = max(cos_distanses)
max_cos

0.9486832980505138

Идентификатор пользователя

In [18]:
user_id = cos_distanses.index(max_cos) + 1
user_id 

8